# Generated by Django 4.2.7 on 2024-03-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludedvenddoc',
            name='doc_id',
            field=models.ForeignKey(blank=True, db_column='docid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.venddoc'),
        ),
        migrations.AlterField(
            model_name='excludedvenddoc',
            name='ku_id',
            field=models.ForeignKey(blank=True, db_column='ku_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.ku'),
        ),
    ]
