# Generated by Django 4.2.7 on 2024-03-12 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, null=True, verbose_name='item_type')),
                ('item_code', models.CharField(blank=True, null=True, verbose_name='item_code')),
                ('item_name', models.CharField(blank=True, null=True, verbose_name='item_name')),
                ('brand', models.CharField(blank=True, null=True, verbose_name='brand')),
                ('producer', models.CharField(blank=True, null=True, verbose_name='producer')),
                ('ku_key', models.ForeignKey(blank=True, db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.ku', verbose_name='КУ')),
            ],
            options={
                'db_table': 'included_condition',
            },
        ),
        migrations.RemoveField(
            model_name='includedproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='includedproduct',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='includedproduct',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='includedproduct',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='includedproduct',
            name='ku_key',
        ),
        migrations.RemoveField(
            model_name='includedproduct',
            name='producer',
        ),
        migrations.AddField(
            model_name='includedproduct',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='includedproduct',
            name='graph_key',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.kugraph', verbose_name='Номер графика'),
        ),
        migrations.AddField(
            model_name='includedproduct',
            name='invoice_id',
            field=models.CharField(blank=True, null=True, verbose_name='Номер накладной'),
        ),
        migrations.AddField(
            model_name='includedproduct',
            name='product_key',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.product', verbose_name='Код продукта'),
        ),
        migrations.AddField(
            model_name='includedproduct',
            name='rec_key',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.venddocline', verbose_name='Номер накладной'),
        ),
        migrations.DeleteModel(
            name='IncludedProductList',
        ),
    ]
