# Generated by Django 4.2.7 on 2024-03-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0004_product_property_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assortment',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='assortment',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='assortment',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='assortment',
            name='avg_sales',
            field=models.FloatField(blank=True, null=True, verbose_name='avg_sales'),
        ),
        migrations.AddField(
            model_name='assortment',
            name='external_code',
            field=models.CharField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='assortment',
            name='multiplicity',
            field=models.FloatField(blank=True, null=True, verbose_name='multiplicity'),
        ),
        migrations.AddField(
            model_name='assortment',
            name='primaryAccountNum',
            field=models.FloatField(blank=True, null=True, verbose_name='primaryAccountNum'),
        ),
        migrations.AddField(
            model_name='assortment',
            name='product_key',
            field=models.CharField(blank=True, null=True, verbose_name='Product_Id'),
        ),
        migrations.AddField(
            model_name='assortment',
            name='retail_price',
            field=models.FloatField(blank=True, null=True, verbose_name='retail_price'),
        ),
        migrations.AddField(
            model_name='assortment',
            name='store_key',
            field=models.BigIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='assortment',
            name='type_assort',
            field=models.CharField(blank=True, null=True, verbose_name=''),
        ),
    ]
