# Generated by Django 4.2.7 on 2024-03-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0005_remove_assortment_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
