# Generated by Django 4.2.7 on 2024-04-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0008_kugraph_date_accrual_alter_kugraph_date_calc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy_key_id', models.BigIntegerField(blank=True, null=True, verbose_name='иерархия')),
                ('category_parent', models.BigIntegerField(blank=True, null=True, verbose_name='Род. категория')),
                ('name', models.CharField(verbose_name='Наименование')),
                ('external_code', models.CharField(verbose_name='Внешний код')),
                ('lvl', models.IntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('external_id', models.BigIntegerField(blank=True, null=True, verbose_name='Внешний id')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
