# Generated by Django 4.2.7 on 2024-04-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0010_product_brand_name_product_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='property_1',
        ),
    ]
