# Generated by Django 4.2.7 on 2024-04-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0012_alter_ku_ku_type_alter_ku_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='includedproduct',
            name='qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
