# Generated by Django 4.2.7 on 2024-04-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0013_includedproduct_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='includedproduct',
            name='qty',
        ),
        migrations.AddField(
            model_name='includedproductlist',
            name='qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
