# Generated by Django 4.2.7 on 2024-04-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0014_remove_includedproduct_qty_includedproductlist_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, null=True, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_category_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='id категории группы'),
        ),
    ]
