# Generated by Django 4.2.7 on 2024-04-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0016_product_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='organization_code',
            field=models.CharField(blank=True, null=True, verbose_name='код организации'),
        ),
    ]
