# Generated by Django 4.2.7 on 2024-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0017_vendor_organization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='venddoc',
            name='fully_factured',
            field=models.CharField(blank=True, null=True, verbose_name='fully factured'),
        ),
        migrations.AddField(
            model_name='venddoc',
            name='purchase_type',
            field=models.CharField(blank=True, null=True, verbose_name='purch type'),
        ),
        migrations.AddField(
            model_name='venddoclines',
            name='entity_id',
            field=models.CharField(blank=True, null=True, verbose_name='entity_id'),
        ),
        migrations.AlterField(
            model_name='venddoclines',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='venddoclines',
            name='amount_vat',
            field=models.FloatField(blank=True, null=True, verbose_name='AmountVAT'),
        ),
        migrations.AlterField(
            model_name='venddoclines',
            name='qty',
            field=models.FloatField(blank=True, null=True, verbose_name='QTY'),
        ),
        migrations.AlterField(
            model_name='venddoclines',
            name='vat',
            field=models.FloatField(blank=True, null=True, verbose_name='VAT'),
        ),
    ]
