# Generated by Django 4.2.7 on 2024-04-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0018_venddoc_fully_factured_venddoc_purchase_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venddoc',
            name='doctype',
            field=models.CharField(blank=True, null=True, verbose_name='DocType'),
        ),
        migrations.AlterField(
            model_name='venddoc',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice_date'),
        ),
        migrations.AlterField(
            model_name='venddoc',
            name='invoice_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Invoice_id'),
        ),
        migrations.AlterField(
            model_name='venddoc',
            name='invoice_name',
            field=models.CharField(blank=True, null=True, verbose_name='Invoice_name'),
        ),
        migrations.AlterField(
            model_name='venddoc',
            name='invoice_number',
            field=models.CharField(blank=True, null=True, verbose_name='Invoice_number'),
        ),
        migrations.AlterField(
            model_name='venddoc',
            name='purch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purch_date'),
        ),
        migrations.AlterField(
            model_name='venddoc',
            name='purch_number',
            field=models.CharField(blank=True, null=True, verbose_name='Purch_number'),
        ),
    ]
