# Generated by Django 4.2.7 on 2024-04-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0019_alter_venddoc_doctype_alter_venddoc_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venddoc',
            name='entity_id',
            field=models.ForeignKey(blank=True, db_column='entity_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.entity'),
        ),
        migrations.AlterField(
            model_name='venddoc',
            name='vendor_id',
            field=models.ForeignKey(blank=True, db_column='vendor_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.vendor'),
        ),
    ]
