# Generated by Django 4.2.7 on 2024-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0020_alter_venddoc_entity_id_alter_venddoc_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venddoclines',
            name='recid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='RecId'),
        ),
    ]
