# Generated by Django 4.2.7 on 2024-04-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0023_excludedproductlist_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excludedproductlist',
            name='graph_id',
        ),
    ]
