# Generated by Django 4.2.7 on 2024-04-15 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0024_remove_excludedproductlist_graph_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='excludedproductlist',
            name='graph_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.kugraph'),
        ),
    ]
