# Generated by Django 4.2.7 on 2024-04-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0025_excludedproductlist_graph_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludedproductlist',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='excludedproductlist',
            name='invoice_id',
            field=models.CharField(blank=True, null=True, verbose_name='Invoice_id'),
        ),
    ]
