# Generated by Django 4.2.7 on 2024-04-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0027_alter_excludedproductlist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excludedvenddoc',
            old_name='doc_id',
            new_name='docid',
        ),
    ]
