# Generated by Django 4.2.7 on 2024-04-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0028_rename_doc_id_excludedvenddoc_docid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ku',
            name='subsidiaries',
            field=models.BooleanField(blank=True, null=True, verbose_name='Дочерние компании'),
        ),
    ]
