# Generated by Django 4.2.7 on 2024-04-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0029_ku_subsidiaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludedproductlist',
            name='graph_id',
            field=models.ForeignKey(blank=True, db_column='graph_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.kugraph'),
        ),
    ]
