# Generated by Django 4.2.7 on 2024-04-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0030_alter_excludedproductlist_graph_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludedproduct',
            name='ku_id',
            field=models.ForeignKey(blank=True, db_column='ku_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.ku'),
        ),
        migrations.AlterField(
            model_name='excludedvenddoc',
            name='docid',
            field=models.ForeignKey(blank=True, db_column='docid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.venddoc'),
        ),
        migrations.AlterField(
            model_name='excludedvenddoc',
            name='ku_id',
            field=models.ForeignKey(blank=True, db_column='ku_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.ku'),
        ),
        migrations.AlterField(
            model_name='includedproduct',
            name='ku_id',
            field=models.ForeignKey(blank=True, db_column='ku_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.ku'),
        ),
        migrations.AlterField(
            model_name='kugraph',
            name='ku_id',
            field=models.ForeignKey(db_column='ku_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.ku'),
        ),
    ]
