# Generated by Django 4.2.7 on 2024-04-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0031_alter_excludedproduct_ku_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, null=True, verbose_name='Код')),
                ('entity_id', models.CharField(blank=True, null=True, verbose_name='Код компании')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Название')),
                ('organization_code', models.CharField(blank=True, null=True, verbose_name='Код организации')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
