# Generated by Django 4.2.7 on 2024-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0032_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(blank=True, null=True, verbose_name='Код услуги')),
                ('service_name', models.CharField(blank=True, null=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
