# Generated by Django 4.2.7 on 2024-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0033_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='article_code',
            field=models.CharField(blank=True, null=True, verbose_name='Код услуги'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_name',
            field=models.CharField(blank=True, null=True, verbose_name='Brand_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
