# Generated by Django 4.2.7 on 2024-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0034_remove_article_name_article_article_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.CharField(blank=True, null=True, verbose_name='Код магазина')),
                ('shop_name', models.CharField(blank=True, null=True, verbose_name='Название')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Адресс')),
            ],
            options={
                'db_table': 'PlaceService',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(blank=True, null=True, verbose_name='Название'),
        ),
    ]
