# Generated by Django 4.2.7 on 2024-04-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0036_alter_placeservice_address_alter_placeservice_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name='истечение срока')),
                ('article_code', models.CharField(blank=True, null=True, verbose_name='Код статьи')),
                ('article_name', models.CharField(blank=True, null=True, verbose_name='Название')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('unit', models.CharField(blank=True, null=True, verbose_name='Единица измерения')),
            ],
            options={
                'db_table': 'price_list',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='article_code',
            field=models.CharField(blank=True, null=True, verbose_name='Код статьи'),
        ),
    ]
