# Generated by Django 4.2.7 on 2024-04-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0037_pricelist_alter_article_article_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(blank=True, null=True, verbose_name='Код статьи')),
                ('article_name', models.CharField(blank=True, null=True, verbose_name='Название статьи')),
                ('service_code', models.CharField(blank=True, null=True, verbose_name='Код услуги')),
                ('service_name', models.CharField(blank=True, null=True, verbose_name='Название услуги')),
                ('ratio', models.FloatField(blank=True, null=True, verbose_name='Коэффициент')),
                ('ku_id', models.CharField(blank=True, null=True, verbose_name='КУ клиента')),
            ],
            options={
                'db_table': 'included_service',
            },
        ),
    ]
