# Generated by Django 4.2.7 on 2024-04-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0038_includedservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='code',
        ),
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='BankBik'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BankName'),
        ),
        migrations.AddField(
            model_name='customer',
            name='corr_account',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='CorrAccount'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, db_column='code', max_length=20, null=True, verbose_name='vendor_id'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dir_party',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='DirParty'),
        ),
        migrations.AddField(
            model_name='customer',
            name='director_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DirectorName'),
        ),
        migrations.AddField(
            model_name='customer',
            name='inn_kpp',
            field=models.CharField(blank=True, max_length=121, null=True, verbose_name='INN/KPP'),
        ),
        migrations.AddField(
            model_name='customer',
            name='urastic_adress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='UrasticAdress'),
        ),
        migrations.AddField(
            model_name='customer',
            name='urastic_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UrasticName'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='entity_id',
            field=models.ForeignKey(blank=True, db_column='entity_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.entity'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization_code',
            field=models.CharField(blank=True, null=True, verbose_name='код организации'),
        ),
    ]
