# Generated by Django 4.2.7 on 2024-04-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0039_remove_customer_code_customer_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
