# Generated by Django 4.2.7 on 2024-04-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0040_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='vendor_id')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('urastic_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='UrasticName')),
                ('inn_kpp', models.CharField(blank=True, max_length=121, null=True, verbose_name='INN/KPP')),
                ('director_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='DirectorName')),
                ('urastic_adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='UrasticAdress')),
                ('account', models.CharField(blank=True, max_length=35, null=True, verbose_name='Account')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='BankName')),
                ('bank_bik', models.CharField(blank=True, max_length=15, null=True, verbose_name='BankBik')),
                ('corr_account', models.CharField(blank=True, max_length=35, null=True, verbose_name='CorrAccount')),
                ('dir_party', models.BigIntegerField(blank=True, null=True, verbose_name='DirParty')),
                ('entity_id', models.ForeignKey(blank=True, db_column='entity_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.entity')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
