# Generated by Django 4.2.7 on 2024-04-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0041_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BankBik'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='corr_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CorrAccount'),
        ),
    ]
