# Generated by Django 4.2.7 on 2024-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0042_alter_customer_account_alter_customer_bank_bik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='entity_id',
            field=models.CharField(blank=True, null=True, verbose_name='Entity'),
        ),
    ]
