# Generated by Django 4.2.7 on 2024-04-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0043_alter_customer_entity_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
