# Generated by Django 4.2.7 on 2024-04-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0046_alter_customer_dir_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuCustomer',
            fields=[
                ('ku_id', models.CharField(editable=False, primary_key=True, serialize=False, verbose_name='ku_id')),
                ('vendor_id', models.CharField(blank=True, null=True, verbose_name='Vendor')),
                ('entity_id', models.CharField(blank=True, null=True, verbose_name='Entity')),
                ('period', models.CharField(max_length=10, verbose_name='Period')),
                ('date_start', models.DateField(verbose_name='Date_start')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Date_end')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('date_actual', models.DateField(blank=True, null=True, verbose_name='Date_actual')),
                ('base', models.FloatField(blank=True, null=True, verbose_name='Base')),
                ('percent', models.IntegerField(blank=True, null=True, verbose_name='Percent')),
                ('graph_exists', models.BooleanField(blank=True, null=True, verbose_name='graph_Exists')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Описание')),
                ('contract', models.CharField(blank=True, null=True, verbose_name='Контракт')),
                ('product_type', models.CharField(blank=True, null=True, verbose_name='Тип продукта')),
                ('docu_account', models.CharField(blank=True, null=True, verbose_name='Номер счета в договоре')),
                ('docu_name', models.CharField(blank=True, null=True, verbose_name='Название договора')),
                ('docu_number', models.CharField(blank=True, null=True, verbose_name='Номер договора')),
                ('docu_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('docu_subject', models.CharField(blank=True, null=True, verbose_name='Предмет договора')),
                ('tax', models.BooleanField(blank=True, null=True, verbose_name='Налог')),
                ('exclude_return', models.BooleanField(blank=True, null=True, verbose_name='Исключать возвраты')),
                ('negative_turnover', models.BooleanField(blank=True, null=True, verbose_name='Отрицательный товарооборот')),
                ('ku_type', models.CharField(blank=True, choices=[('Ретро-бонус', 'Ретро-бонус'), ('Услуга', 'Услуга')], null=True, verbose_name='Тип КУ')),
                ('pay_method', models.CharField(blank=True, choices=[('Взаимозачет', 'Взаимозачет'), ('Оплата', 'Оплата')], null=True, verbose_name='Способ оплаты')),
                ('subsidiaries', models.BooleanField(blank=True, null=True, verbose_name='Дочерние компании')),
            ],
            options={
                'db_table': 'ku_customer',
            },
        ),
        migrations.CreateModel(
            name='KuGraphCustomer',
            fields=[
                ('graph_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Graph_id')),
                ('vendor_id', models.CharField(blank=True, null=True, verbose_name='Vendor')),
                ('ku_id', models.CharField(blank=True, null=True, verbose_name='ku')),
                ('period', models.CharField(blank=True, max_length=10, null=True, verbose_name='Period')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Date_start')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Date_end')),
                ('date_calc', models.DateTimeField(blank=True, null=True, verbose_name='Date_calc')),
                ('date_accrual', models.DateField(blank=True, null=True, verbose_name='Дата начисления')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('sum_calc', models.FloatField(blank=True, null=True, verbose_name='Sum_calc')),
                ('sum_bonus', models.FloatField(blank=True, null=True, verbose_name='Sum_bonus')),
                ('percent', models.IntegerField(blank=True, null=True, verbose_name='Percent')),
                ('sum_approved', models.FloatField(blank=True, null=True, verbose_name='Sum_approved')),
            ],
            options={
                'db_table': 'ku_graph_cuctomer',
            },
        ),
    ]
