# Generated by Django 4.2.7 on 2024-05-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0047_kucustomer_kugraphcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='ku_id',
        ),
        migrations.CreateModel(
            name='ManagerKuCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ku_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.kucustomer')),
                ('manager_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.manager')),
            ],
            options={
                'db_table': 'manager_ku_customer',
            },
        ),
        migrations.CreateModel(
            name='ManagerKu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ku_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.ku')),
                ('manager_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.manager')),
            ],
            options={
                'db_table': 'manager_ku',
            },
        ),
    ]
