# Generated by Django 4.2.7 on 2024-05-20 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0048_remove_manager_ku_id_managerkucustomer_managerku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kucustomer',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='kugraphcustomer',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='kucustomer',
            name='customer_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.vendor'),
        ),
        migrations.AddField(
            model_name='kugraphcustomer',
            name='customer_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.vendor'),
        ),
        migrations.AlterField(
            model_name='kucustomer',
            name='entity_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.entity'),
        ),
        migrations.AlterField(
            model_name='kugraphcustomer',
            name='ku_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.kucustomer'),
        ),
    ]
