# Generated by Django 4.2.7 on 2024-05-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0049_remove_kucustomer_vendor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialCustomer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('counterparty_name', models.CharField(blank=True, null=True)),
                ('counterparty_post', models.CharField(blank=True, null=True)),
                ('counterparty_docu', models.CharField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, null=True)),
                ('entity_post', models.CharField(blank=True, null=True)),
                ('entity_docu', models.CharField(blank=True, null=True)),
                ('ku_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'official_customers',
            },
        ),
        migrations.RenameField(
            model_name='kucustomer',
            old_name='base',
            new_name='pay_sum',
        ),
        migrations.RemoveField(
            model_name='kucustomer',
            name='docu_name',
        ),
        migrations.RemoveField(
            model_name='kucustomer',
            name='exclude_return',
        ),
        migrations.RemoveField(
            model_name='kucustomer',
            name='ku_type',
        ),
        migrations.RemoveField(
            model_name='kucustomer',
            name='negative_turnover',
        ),
        migrations.RemoveField(
            model_name='kucustomer',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='kucustomer',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='kucustomer',
            name='tax',
        ),
    ]
