# Generated by Django 4.2.7 on 2024-05-20 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0051_includedservice_article_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='includedservice',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='includedservice',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='kucustomer',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='kucustomer',
            old_name='entity_id',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='kugraphcustomer',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='kugraphcustomer',
            old_name='ku_id',
            new_name='ku',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='includedservice',
            name='article_code',
        ),
        migrations.RemoveField(
            model_name='includedservice',
            name='article_name',
        ),
        migrations.RemoveField(
            model_name='includedservice',
            name='ku_id',
        ),
        migrations.RemoveField(
            model_name='includedservice',
            name='service_code',
        ),
        migrations.RemoveField(
            model_name='includedservice',
            name='service_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.entity'),
        ),
        migrations.AddField(
            model_name='includedservice',
            name='ku',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='LAMA_ucup.kucustomer'),
        ),
    ]
