# Generated by Django 4.2.7 on 2024-05-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0052_rename_article_id_includedservice_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerku',
            old_name='ku_id',
            new_name='ku',
        ),
        migrations.RenameField(
            model_name='managerku',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='managerkucustomer',
            old_name='ku_id',
            new_name='ku',
        ),
        migrations.RenameField(
            model_name='managerkucustomer',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.AlterModelTable(
            name='officialcustomer',
            table='official_customer',
        ),
    ]
