# Generated by Django 4.2.7 on 2024-05-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0053_rename_ku_id_managerku_ku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='includedproduct',
            old_name='in_prod_id',
            new_name='id',
        ),
    ]
