# Generated by Django 4.2.7 on 2024-05-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0054_rename_in_prod_id_includedproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includedproduct',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
