# Generated by Django 4.2.7 on 2024-05-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0055_alter_includedproduct_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='id',
            new_name='manager',
        ),
        migrations.AlterField(
            model_name='kugraphcustomer',
            name='date_calc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата расчета'),
        ),
        migrations.CreateModel(
            name='IncludedVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('type_partner', models.CharField(blank=True, null=True)),
                ('code_partner', models.CharField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.entity')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.vendor')),
            ],
            options={
                'db_table': 'included_vendor',
            },
        ),
    ]
