# Generated by Django 4.2.7 on 2024-05-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0056_rename_id_manager_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager',
            new_name='id',
        ),
    ]
