# Generated by Django 4.2.7 on 2024-05-26 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0057_rename_manager_manager_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedVendorCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('type_partner', models.CharField(blank=True, null=True)),
                ('code_partner', models.CharField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.entity')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.vendor')),
            ],
            options={
                'db_table': 'included_vendor_customer',
            },
        ),
    ]
