# Generated by Django 4.2.7 on 2024-05-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0060_remove_includedvendor_code_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venddoc',
            name='sum_product',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма количества продуктов'),
        ),
    ]
