# Generated by Django 4.2.7 on 2024-05-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0061_venddoc_sum_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venddoclines',
            name='docid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.venddoc'),
        ),
    ]
