# Generated by Django 4.2.7 on 2024-05-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0062_alter_venddoclines_docid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venddoc',
            old_name='sum_product',
            new_name='sum_qty',
        ),
    ]
