# Generated by Django 4.2.7 on 2024-05-30 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0063_rename_sum_product_venddoc_sum_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedVenddoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(blank=True, null=True, verbose_name='Сумма без ндс')),
                ('sum_tax', models.FloatField(blank=True, null=True, verbose_name='Сумма с ндс')),
                ('graph', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.kugraph')),
                ('venddoc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.venddoc')),
            ],
        ),
    ]
