# Generated by Django 4.2.7 on 2024-05-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0064_includedvenddoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassifierTest',
        ),
        migrations.AlterModelTable(
            name='includedvenddoc',
            table='included_venddoc',
        ),
    ]
