# Generated by Django 4.2.7 on 2024-05-31 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0065_delete_classifiertest_alter_includedvenddoc_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includedproductlist',
            name='invoice_id',
            field=models.ForeignKey(blank=True, db_column=' invoice_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LAMA_ucup.venddoc'),
        ),
    ]
