# Generated by Django 4.2.7 on 2024-06-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0066_alter_includedproductlist_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='includedvenddoc',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='includedvenddoc',
            name='sum_tax',
        ),
    ]
